In [1]:
import pandas as pd

In [2]:
stopsData1 = pd.read_excel("stopsData1_0319.xlsx")
stopsData2 = pd.read_excel("stopsData2_0319.xlsx")
df = stopsData1.merge(stopsData2,how='inner',on='stop_id')

In [35]:
df.groupby(['driver_sex','ticket'])['stop_id'].count()

driver_sex  ticket
f           0         659
            1         190
m           0         776
            1         515
Name: stop_id, dtype: int64

In [26]:
df

,stop_id,officer_id,driver_id,driver_age,driver_sex,ticket,ward,isMale
0,7406,B,3566,33,m,0,1,1.0
1,3364,A,9243,28,m,1,7,1.0
2,1934,D,1296,66,m,0,3,1.0
3,2807,E,14277,28,m,0,8,1.0
4,9974,D,2493,55,m,0,2,1.0
5,5339,A,5785,48,m,1,2,1.0
6,9579,C,21165,52,m,1,4,1.0
7,34,B,3794,60,f,0,6,0.0
8,4172,A,14186,34,f,0,1,0.0
9,6845,D,16307,51,m,1,1,1.0
10,4730,C,20934,48,m,0,3,1.0
11,8473,C,12548,20,f,0,4,0.0
12,4977,D,13964,69,m,0,8,1.0
13,1909,E,8859,57,f,1,7,0.0
14,9201,D,2998,63,f,0,2,0.0
15,5193,B,1488,75,m,0,7,1.0
16,1330,D,6147,53,m,1,8,1.0
17,1732,A,5167,55,m,1,4,1.0
18,5951,B,15470,26,m,0,3,1.0
19,9951,B,17530,54,m,1,1,1.0
20,5182,C,15262,59,f,1,1,0.0
21,1664,C,10535,44,f,1,4,0.0
22,6930,E,1588,62,f,0,1,0.0
23,1549,B,2069,61,f,1,6,0.0
24,8523,C,4824,50,m,1,6,1.0
25,6918,E,15471,22,f,0,5,0.0
26,6894,A,5508,57,m,0,3,1.0
27,6895,C,16398,21,m,0,2,1.0
28,1046,D,10921,21,m,0,2,1.0
29,8117,B,8766,75,f,0,8,0.0
...,...,...,...,...,...,...,...,...
2110,2469,E,13197,16,f,0,1,0.0
2111,4689,A,49,44,m,1,7,1.0
2112,4315,E,10399,35,m,1,2,1.0
2113,9157,B,2335,54,f,0,5,0.0
2114,9077,E,12524,40,m,1,7,1.0
2115,1618,D,16777,45,f,1,8,0.0
2116,7723,A,12141,45,f,1,5,0.0
2117,2684,A,15052,24,m,0,5,1.0
2118,1945,B,15223,41,f,0,1,0.0
2119,6925,E,14701,34,f,0,3,0.0
2120,9741,B,6372,69,m,1,3,1.0
2121,8068,C,21119,60,m,1,6,1.0
2122,9704,D,20534,37,m,1,5,1.0
2123,2146,D,750,66,m,0,6,1.0
2124,8464,A,16181,40,m,1,4,1.0
2125,1558,D,20661,53,f,1,5,0.0
2126,9424,D,951,50,m,1,2,1.0
2127,2082,A,9218,72,m,0,3,1.0
2128,6498,A,10984,55,f,1,8,0.0
2129,2216,E,4999,76,m,0,6,1.0
2130,475,A,11502,28,m,0,7,1.0
2131,517,D,15071,74,m,1,4,1.0
2132,8894,E,2918,59,f,1,8,0.0
2133,1005,C,12537,58,m,0,2,1.0
2134,1259,B,20944,24,m,0,2,1.0
2135,5492,E,21244,44,m,1,3,1.0
2136,1676,C,20611,66,m,0,6,1.0
2137,1865,C,11479,26,m,0,7,1.0
2138,3572,A,11002,70,m,0,3,1.0
2139,7543,A,9784,37,f,0,5,0.0

In [4]:
# How many traffic stops are there in the data? 
df.shape

(2140, 7)

In [5]:
# How many different drivers were stopped? 
df.driver_id.nunique()

2034

In [6]:
# What’s the average age of those stopped? 
df.driver_age.mean()

47.11822429906542

In [7]:
# What percentage of stops are men? 
df[df.driver_sex=='m'].shape[0]/df.stop_id.nunique()

0.6032710280373832

In [8]:
# Which ward has highest average age of those stopped? 
df.groupby(['ward'])['driver_age'].mean().sort_values(ascending=False)

ward
8    50.905882
6    49.923695
7    48.432836
3    46.878788
5    46.021053
4    45.571429
2    44.869565
1    44.867188
Name: driver_age, dtype: float64

In [9]:
'''Using this model, if driver A is x years old, and driver B is x + 10 years old, 
how much more or less likely to receive a ticket is driver B than driver A?'''
import statsmodels.api as st
df['isMale']=pd.get_dummies(df.driver_sex, dtype=float)['m']
x = df.loc[:,['driver_age','isMale']]
x = st.add_constant(x, prepend = False)
y = df.ticket
mdl = st.MNLogit(y, x)

In [10]:
mdl_fit = mdl.fit()
mdl_fit.summary()

Optimization terminated successfully.
         Current function value: 0.607251
         Iterations 5

<class 'statsmodels.iolib.summary.Summary'>
"""
                          MNLogit Regression Results
==============================================================================
Dep. Variable:                 ticket   No. Observations:                 2140
Model:                        MNLogit   Df Residuals:                     2137
Method:                           MLE   Df Model:                            2
Date:                Fri, 22 Mar 2019   Pseudo R-squ.:                 0.04186
Time:                        02:14:29   Log-Likelihood:                -1299.5
converged:                       True   LL-Null:                       -1356.3
                                        LLR p-value:                 2.206e-25
==============================================================================
  ticket=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
driver_age     0.0185      0.003      6.282      0.000       0.013       0.024
isMale         0.8512      0.101      8.420      0.000       0.653       1.049
const         -2.1438      0.169    -12.677      0.000      -2.475      -1.812
==============================================================================
"""

Using this model, if driver A is x years old, and driver B is x + 10 years old, how much more or less likely to receive a ticket is driver B than driver A?

In [61]:
AGE = 20
driverA= mdl_fit.predict([AGE,0,1])[0][1]
driverB=mdl_fit.predict([AGE+10,0,1])[0][1]
driverB/driverA

1.1692118876476174

From the estimated model, what is the expected probability that a 30-year old female who is stopped will receive a ticket?

In [27]:
mdl_fit.predict([30,0,1])

array([[0.83024437, 0.16975563]])

From the estimated model, how much more or less likely are men to receive tickets than women of the same age?

In [55]:
AGE=0
M = mdl_fit.predict([AGE,1,1])[0][1]
F = mdl_fit.predict([AGE,0,1])[0][1]
M/F

2.0532528753649637